<div class="grid input-box lesser">
    <div class="row">
        <div class="col whole">
            <div class="modal-box">
                <form>
                    <fieldset>
                        <div class="row">
                            <div class="col two-thirds  mutableContent">
                                <div id="text-input">
                                    <div id="title-input">
                                        <label>Title
                                            <span class="small">(optional)</span>
                                        </label>
                                        <input type="text" name="email" value="" id="title" style="width: 525px" />
                                    </div>
                                    <label>Post
                                        <span class="small"> &HorizontalLine; <a href="#global-input" dref="toggle">Click here to add a title, snap, location, tags etc.</a></span>
                                    </label>
                                    <textarea name="ptext" id="ptext" style="width: 100%;min-height: 205px"></textarea>
                                </div>

                                <div id="extras-input">
                                    <hr class="hr-ccc" />

                                    <label> Add a photo 
                                        <span class="small"> &HorizontalLine; <a href="#">Upload from URL instead?</a></span>
                                    </label>
                                    <input type="file" name="email" value="" id="title" style="width: 100%" />
                                    <label>Excerpt
                                        <span class="small">(optional)</span>
                                    </label>
                                    <textarea name="ptext" id="ptext" style="width: 100%;min-height: 92px"></textarea>
                                    <label>Tags
                                        <span class="small"></span>
                                    </label>
                                    <textarea name="ptext" id="ptext" style="width: 100%;min-height: 41px" placeholder="<?php echo _('Tag your friends, or by topic. Seperate each tag with a comma.'); ?>"></textarea>

                                </div>
                            </div>
                            <div class="col two-sixths wrap">
                                <div style="padding: 0 0 0 15px">
                                    <div id="location-input">
                                        <label>Location
                                            <span class="small">(optional)</span>
                                        </label>
                                        <input type="text" name="email" class="localpicker" value="" id="title" style="width: 245px" />
                                    </div>
                                    <label>Map
                                        <span class="small"></span>
                                    </label>
                                    <div class="mapbox" style="background: #eee;min-height: 205px; border: 1px solid #ccc; margin-bottom: 0px">
                                        &nbsp;
                                    </div> 





                                </div>
                            </div>
                        </div>
                        <hr class="hr-ccc" /> 
                        <div class="row">
                            <div class="col two-sixths  mutableContent"> 
                                <button class="button medium"><?php echo _("Publish"); ?></button>
                                <button class="button medium"><?php echo _("Peview"); ?></button>
                            </div>                        
                            <div class="col sixth">

                                <div id="date-input">
                                    <input type="text" name="email" class="datepicker" value="<?php echo date('m/d/Y'); ?>" id="title" style="width: 90%" />
                                </div>
                            </div>
                            <div class="col sixth">
                                <div id="section-input">
                                    <select style="width: 100%">
                                        <option value="1">My Profile</option>
                                        <option value="1">Stupid Women&trade; (Group)</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col two-sixths wrap">
                                <div style="padding: 0 0 0 15px">
                                    <!--<label>Publish to</label>-->
                                    <select style="width: 100%">
                                        <option value="1">Make post public</option>
                                        <option value="1">Make visible to followers only</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>