<div class="table" style="border-top: 1px solid #eee; max-width: 530px">
    <!--Comments Roll-->
    <div class="tableRow" style="padding: 10px 0; border-bottom: 1px dotted #ddd">
        <div class="tableRowCell" style="width: 10%; min-width: 50px"><img src="/glycine/img/sample_user.png" alt="Sample User Avatar" width="35" style="border: 1px solid #ccc; padding: 2px"></div>
        <div class="tableRowCell" style="width: 90%">
            <p style="line-height: 150%"><a href="#">John Doe</a> - It does not matter how slow you go so long as you do not stop. And always remember that when trouble comes, i will always be on your side, and will never let you go</p>
            <div style="color: #999; margin-bottom: 3px">
                <span>13 mins ago</span>
            </div>
        </div>
        <div class="clear"></div>
    </div>

    <div class="tableRow" style="padding: 10px 0; border-bottom: 1px dotted #ddd">
        <div class="tableRowCell" style="width: 10%; min-width: 50px"><img src="/glycine/img/sample_user.png" alt="Sample User Avatar" width="35" style="border: 1px solid #ccc; padding: 2px"></div>
        <div class="tableRowCell" style="width: 90%">
            <p style="line-height: 150%"><a href="#">John Doe</a> - It does not matter how slow you go so long as you do not stop. And always remember that when trouble comes, i will always be on your side, and will never let you go</p>
            <div style="color: #999; margin-bottom: 3px">
                <span>13 mins ago</span>
            </div>
        </div>
        <div class="clear"></div>
    </div>

    <div class="tableRow" style="padding: 10px 0; border-bottom: 1px dotted #ddd">
        <div class="tableRowCell" style="width: 10%; min-width: 50px"><img src="/glycine/img/sample_user.png" alt="Sample User Avatar" width="35" style="border: 1px solid #ccc; padding: 2px"></div>
        <div class="tableRowCell" style="width: 90%">
            <p style="line-height: 150%"><a href="#">John Doe</a> - It does not matter how slow you go so long as you do not stop. And always remember that when trouble comes, i will always be on your side, and will never let you go</p>
            <div style="color: #999; margin-bottom: 3px">
                <span>13 mins ago</span>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <!--/Comments Roll-->

    <!--Comments Input-->
    <div class="tableRow" style="padding: 10px 10px 1px 10px; background: #eee">
        <form>
            <input style="width: 100%;" type="text" placeholder="<?php echo _('Add your comment'); ?>" />
        </form>
    </div>
    <!--/Comments Input-->
</div>