<div class="grid">
    <div class="row">
        <div class="col quater">
            <div style="margin-bottom: 10px">
                <img  width="60" height="60" style="width: 60px; height: 60px; margin-right: 10px; float: left;" src="http://localhost/joomla/components/com_tuiyo/files/avatars/62/thumb200/62_255_6a00e54fb7301c88340133f61013eb970b800wi.jpg" />
                Navigator
                <div class="clearFloat"></div>
            </div>
            <nav id="main-side-nav">
                <div>
                    <span class="smaller bold"><?php echo _('BOOKMARKS'); ?></span>
                    <div>
                        <ul>
                            <li class="cnt-new"><a href="#"><?php echo _('Add new...'); ?></a></li>
                            <li class="cnt-articles"><a href="#"><?php echo _('Articles'); ?> <span class="smaller bold" rel="tooltip" title="<?php echo _('New'); ?>">30</span></a></li>
                            <li class="cnt-photos"><a href="#"><?php echo _('Photos'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('New'); ?>">100+</span></a></li>
                            <li class="cnt-videos"><a href="#"><?php echo _('Videos'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('New'); ?>">20</span></a></li>
                            <li class="cnt-audio"><a href="#"><?php echo _('Audio'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('New'); ?>">31</span></a></li>
                            <li class="cnt-questions"><a href="#"><?php echo _('Questions'); ?></a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="col three-quaters">
            <div class="padding-left-20">
                <div class="titlebar">
                    <div id="content-announce">

                        <h1>Latest Broadcasts</h1>
                        <p style="line-height: 1em"><span class="locale"></span> <span class="locale-time">Wednesday, 28 September</span></p>
                    </div>
                </div>

                <!-- Notification -->

                <!--    <a href="#" class="close-notification" title="Hide Notification" rel="tooltip">x</a>-->
                <p align="center" class="notification information"><a href="#">You have <span style="background-color: red; color: #fff; font-weight: bold; padding: 2px">13</span> new and unread posts</a></p>

                <!-- /Notification -->
                <ul class="stream-posts" id="posts">
                    <li class="stream-posts-li QUOTE wisdom new_post latest">
                        <div class="stream-posts-box">
                            <div class="stream-posts-box-side">
                                <div class="stream-posts-box-side-type"><img src="http://localhost/joomla/components/com_tuiyo/files/avatars/62/thumb200/62_255_6a00e54fb7301c88340133f61013eb970b800wi.jpg" width="60"></div>
                                <a class="stream-posts-box-side-perma" href="http://demo.tumblr.com/post/236/it-does-not-matter-how-slow-you-go-so-long-as-you"></a>
                            </div>
                            <div class="stream-posts-box-content">

                                <blockquote><span class="QUOTE_quotation">&rdquo;</span>It does not matter how slow you go so long as you do not stop.</blockquote>
                                Wisdom of&nbsp;<a href="#" title="http://en.wikipedia.org/wiki/Confucius">Confucius</a>
                                <div class="stream-posts-box-content-details">
                                    <div class="stream-posts-box-content-tags">
                                        <span class="stream-posts-box-content-details-icon"></span>
                                        <p>Tags: <a href="#" title="http://demo.tumblr.com/tagged/wisdom/chrono">wisdom</a>, </p>
                                    </div>
                                </div>
                                <div class="stream-posts-box-content-details">
                                    <div class="stream-posts-box-content-details-upper">
                                        <div class="stream-posts-box-content-timestamp">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://john-appleseed.tumblr.com/" target="_blank">John Doe</a> - <a href="#" title="/day/2006/11/08">4 years ago</a></p>
                                        </div>
                                        <div class="stream-posts-box-content-notes">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://demo.tumblr.com/post/236/it-does-not-matter-how-slow-you-go-so-long-as-you#notes">6,909 notes</a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="stream-posts-box-content" style="margin-top: 10px">
                                    <?php echo $this->layout('comments', 'content'); ?>
                                </div>
                            </div>
                        </div>
                        <div class="stream-posts-break"></div>
                    </li>
                    <li class="stream-posts-li PHOTO mareen_fischinger new_york_city times_square new_post">
                        <div class="stream-posts-box">
                            <div class="stream-posts-box-side">
                                <div class="stream-posts-box-side-type"><img src="http://localhost/joomla/components/com_tuiyo/files/avatars/62/thumb200/62_255_6a00e54fb7301c88340133f61013eb970b800wi.jpg" width="60"></div>
                                <a class="stream-posts-box-side-perma" href="http://demo.tumblr.com/post/459265350/passing-through-times-square-by-mareen-fischinger"></a>
                            </div>
                            <div class="stream-posts-box-content">

                                <div class="PHOTO-display">
                                    <div class="PHOTO-display-width">
                                        <a class="PHOTO-display-high-res" href="http://demo.tumblr.com/photo/1280/459265350/1/tumblr_kzjlfiTnfe1qz4rgh"></a>
                                        <a href="#" title="http://demo.tumblr.com/photo/1280/459265350/1/tumblr_kzjlfiTnfe1qz4rgh"><img alt="Passing through Times Square by&nbsp;Mareen Fischinger" src="http://26.media.tumblr.com/tumblr_kzjlfiTnfe1qz4rgho1_500.jpg"></a>
                                    </div>
                                </div>
                                <p>Passing through Times Square by&nbsp;<a href="#" title="http://www.mareenfischinger.com/">Mareen Fischinger</a></p>

                                <div class="stream-posts-box-content-details">
                                    <div class="stream-posts-box-content-tags">
                                        <span class="stream-posts-box-content-details-icon"></span>
                                        <p>Tags: <a href="#" title="http://demo.tumblr.com/tagged/Mareen_Fischinger/chrono">Mareen Fischinger</a>, <a href="#" title="http://demo.tumblr.com/tagged/New_York_City/chrono">New York City</a>, <a href="#" title="http://demo.tumblr.com/tagged/Times_Square/chrono">Times Square</a>, </p>
                                    </div>
                                </div>
                                <div class="stream-posts-box-content-details">
                                    <div class="stream-posts-box-content-details-upper">
                                        <div class="stream-posts-box-content-timestamp">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://john-appleseed.tumblr.com/" target="_blank">John Doe</a> - <a href="#" title="/day/2006/11/08">4 years ago</a></p>
                                        </div>
                                        <div class="stream-posts-box-content-notes">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://demo.tumblr.com/post/236/it-does-not-matter-how-slow-you-go-so-long-as-you#notes">6,909 notes</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="stream-posts-break"></div>
                    </li>
                    <li class="stream-posts-li LINK  new_post">
                        <div class="stream-posts-box">
                            <div class="stream-posts-box-side">
                                <div class="stream-posts-box-side-type"><img src="http://localhost/joomla/components/com_tuiyo/files/avatars/62/thumb200/62_255_6a00e54fb7301c88340133f61013eb970b800wi.jpg" width="60"></div>
                                <a class="stream-posts-box-side-perma" href="http://demo.tumblr.com/post/234/my-favorite-web-site"></a>
                            </div>
                            <div class="stream-posts-box-content">

                                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                                <div class="stream-posts-box-content-details">
                                    <div class="stream-posts-box-content-details-upper">
                                        <div class="stream-posts-box-content-timestamp">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://john-appleseed.tumblr.com/" target="_blank">John Doe</a> - <a href="#" title="/day/2006/11/08">4 years ago</a></p>
                                        </div>
                                        <div class="stream-posts-box-content-notes">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://demo.tumblr.com/post/236/it-does-not-matter-how-slow-you-go-so-long-as-you#notes">6,909 notes</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="stream-posts-break"></div>
                    </li>
                    <li class="stream-posts-li CHAT funny new_post">
                        <div class="stream-posts-box">
                            <div class="stream-posts-box-side">
                                <div class="stream-posts-box-side-type"><img src="http://localhost/joomla/components/com_tuiyo/files/avatars/62/thumb200/62_255_6a00e54fb7301c88340133f61013eb970b800wi.jpg" width="60"></div>
                                <a class="stream-posts-box-side-perma" href="http://demo.tumblr.com/post/233/jack-hey-you-know-what-sucks-lindsey"></a>
                            </div>
                            <div class="stream-posts-box-content">

                                <ul>
                                    <li class="odd">
                                        <strong>Jack:</strong> Hey, you know what sucks?
                                    </li>
                                    <li class="even">
                                        <strong>Lindsey:</strong> vaccuums
                                    </li>
                                    <li class="odd ">
                                        <strong>Jack:</strong> Hey, you know what sucks in a metaphorical sense?
                                    </li>
                                    <li class="even">
                                        <strong>Lindsey:</strong> black holes
                                    </li>
                                    <li class="odd">
                                        <strong>Jack:</strong> Hey, you know what just isn't cool?
                                    </li>
                                    <li class="even">
                                        <strong>Lindsey:</strong> lava?
                                    </li>
                                </ul>
                                <div class="stream-posts-box-content-details">
                                    <div class="stream-posts-box-content-tags">
                                        <span class="stream-posts-box-content-details-icon"></span>
                                        <p>Tags: <a href="#" title="http://demo.tumblr.com/tagged/funny/chrono">funny</a>, </p>
                                    </div>
                                </div>
                                <div class="stream-posts-box-content-details">
                                    <div class="stream-posts-box-content-details-upper">
                                        <div class="stream-posts-box-content-timestamp">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://john-appleseed.tumblr.com/" target="_blank">John Doe</a> - <a href="#" title="/day/2006/11/08">4 years ago</a></p>
                                        </div>
                                        <div class="stream-posts-box-content-notes">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://demo.tumblr.com/post/236/it-does-not-matter-how-slow-you-go-so-long-as-you#notes">6,909 notes</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="stream-posts-break"></div>
                    </li>
                    <li class="stream-posts-li AUDIO reblog new_post">
                        <div class="stream-posts-box">
                            <div class="stream-posts-box-side">
                                <div class="stream-posts-box-side-type"><img src="http://localhost/joomla/components/com_tuiyo/files/avatars/62/thumb200/62_255_6a00e54fb7301c88340133f61013eb970b800wi.jpg" width="60"></div>
                                <a class="stream-posts-box-side-perma" href="http://demo.tumblr.com/post/459260683/allison-weiss-fingers-crossed"></a>
                            </div>
                            <div class="stream-posts-box-content">

                                <div class="AUDIO_info">
                                    <div class="AUDIO_info_album">
                                        <div class="AUDIO_info_album_overlay"></div>
                                        <img alt="" src="http://28.media.tumblr.com/tumblr_ksc4i2SkVU1qz8ouqo1_r2_cover.jpg">
                                        <div class="AUDIO_info_album_none"></div>
                                    </div>
                                    <div class="AUDIO_info_float">
                                        <div class="AUDIO_info_player">
                                            <div class="AUDIO_info_player_embed">
                                                <script type="text/javascript" language="javascript" src="http://assets.tumblr.com/javascript/tumblelog.js?542"></script><span id="audio_player_459260683"><div class="audio_player"><embed type="application/x-shockwave-flash" src="http://assets.tumblr.com/swf/audio_player.swf?audio_file=http://www.tumblr.com/audio_file/459260683/tumblr_ksc4i2SkVU1qz8ouq&amp;color=E4E4E4" height="27" width="207" quality="best"></div></span><script type="text/javascript">/*<![CDATA[*/replaceIfFlash(9,"audio_player_459260683",'\x3cdiv class=\x22audio_player\x22\x3e<embed type="application/x-shockwave-flash" src="http://assets.tumblr.com/swf/audio_player.swf?audio_file=http://www.tumblr.com/audio_file/459260683/tumblr_ksc4i2SkVU1qz8ouq&color=E4E4E4" height="27" width="207" quality="best"></embed>\x3c/div\x3e');/*]]>*/</script>
                                            </div>
                                        </div>
                                        <div class="AUDIO_info_ta">
                                            <div class="AUDIO_info_track">
                                                <div class="AUDIO_info_none">Unknown</div>
                                                <div class="AUDIO_info_overlay">Fingers Crossed</div>
                                            </div>
                                            <div class="AUDIO_info_artist">
                                                <div class="AUDIO_info_none">Unknown</div>
                                                <div class="AUDIO_info_overlay"><a href="#" title="http://last.fm/artist/Allison Weiss" target="_blank">Allison Weiss</a></div>
                                            </div>
                                        </div>
                                        <div class="AUDIO_info_plays">
                                            <div class="AUDIO_info_plays_count">1,144,240</div>
                                            <div class="AUDIO_info_plays_label" style="text-transform:lowercase">Plays</div>
                                        </div>
                                    </div>
                                </div>
                                <p><strong><a href="#" title="http://allisonweiss.tumblr.com/">Allison Weiss</a>&nbsp;—</strong> Fingers Crossed</p>
                                <div class="stream-posts-box-content-details">
                                    <div class="stream-posts-box-content-details-upper">
                                        <div class="stream-posts-box-content-timestamp">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://john-appleseed.tumblr.com/" target="_blank">John Doe</a> - <a href="#" title="/day/2006/11/08">4 years ago</a></p>
                                        </div>
                                        <div class="stream-posts-box-content-notes">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://demo.tumblr.com/post/236/it-does-not-matter-how-slow-you-go-so-long-as-you#notes">6,909 notes</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="stream-posts-break"></div>
                    </li>
                    <li class="stream-posts-li TEXT new_post">
                        <div class="stream-posts-box">
                            <div class="stream-posts-box-side">
                                <div class="stream-posts-box-side-type"><img src="http://localhost/joomla/components/com_tuiyo/files/avatars/62/thumb200/62_255_6a00e54fb7301c88340133f61013eb970b800wi.jpg" width="60"></div>
                                <a class="stream-posts-box-side-perma" href="http://demo.tumblr.com/post/232/an-example-post"></a>
                            </div>
                            <div class="stream-posts-box-content">


                                <p>Lorem ipsum dolor sit amet, consectetuer <a href="#" title="/">adipiscing elit</a>. Aliquam nisi lorem, pulvinar id, commodo feugiat, vehicula et, mauris. Aliquam mattis porta urna. Maecenas dui neque, rhoncus sed, vehicula vitae, auctor at, nisi. Aenean id massa ut lacus molestie porta. Curabitur sit amet quam id libero suscipit venenatis.</p>
                                <ul><li>Lorem ipsum dolor sit amet.</li>
                                    <li>Consectetuer adipiscing elit. </li>
                                    <li>Nam at tortor quis ipsum tempor aliquet.</li>
                                </ul><p>Cum sociis <a href="#" title="/">natoque penatibus</a> et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse sed ligula. Sed volutpat odio non turpis gravida luctus. Praesent elit pede, iaculis facilisis, vehicula mattis, tempus non, arcu.</p>
                                <blockquote>Donec placerat mauris commodo dolor. Nulla tincidunt. Nulla vitae augue.</blockquote>
                                <p>Suspendisse ac pede. Cras <a href="#" title="/">tincidunt pretium</a> felis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque porttitor mi id felis. Maecenas nec augue. Praesent a quam pretium leo congue accumsan.</p>
                                <div class="stream-posts-box-content-details">
                                    <div class="stream-posts-box-content-details-upper">
                                        <div class="stream-posts-box-content-timestamp">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://john-appleseed.tumblr.com/" target="_blank">John Doe</a> - <a href="#" title="/day/2006/11/08">4 years ago</a></p>
                                        </div>
                                        <div class="stream-posts-box-content-notes">
                                            <span class="stream-posts-box-content-details-icon"></span>
                                            <p><a href="#" title="http://demo.tumblr.com/post/236/it-does-not-matter-how-slow-you-go-so-long-as-you#notes">6,909 notes</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="stream-posts-break"></div>
                    </li>
                    <li class="stream-posts-li TEXT" style="list-style: none">
                        
                        <div class="stream-posts-box-content">
                            <a href="/page/2" style="text-align: center; line-height: 150%" class="button">Load older posts...</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>