<ol class="stream-items" id="main-stream">
    <li class="stream-item-li">
        <div class="stream-item-container">
            <div class="stream-item-header">
                <a class="publisher-profile" href="#">
                    <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                    <strong class="profile-name">Livingstone Fultang</strong>
                    <span class="profile-nameid">@drstonyhills</span>
                </a>
                <small class="published-time">
                    <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                </small>
                <ul class="actions">
                    <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                    <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                    <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                    <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                </ul>
            </div>
            <div class="stream-item-body wrapword">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
            <div class="stream-item-footer">
                <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
            </div>
        </div>
    </li>
    <li class="stream-item-li">
        <div class="stream-item-container">
            <div class="stream-item-header">
                <a class="publisher-profile" href="#">
                    <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                    <strong class="profile-name">Livingstone Fultang</strong>
                    <span class="profile-nameid">@drstonyhills</span>
                </a>
                <small class="published-time">
                    <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                </small>
                <ul class="actions">
                    <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                    <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                    <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                    <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                </ul>
            </div>
            <div class="stream-item-body wrapword">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
            <div class="stream-item-footer">
                <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
            </div>
        </div>
    </li>
    <li class="stream-item-li">
        <div class="stream-item-container">
            <div class="stream-item-header">
                <a class="publisher-profile" href="#">
                    <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                    <strong class="profile-name">Livingstone Fultang</strong>
                    <span class="profile-nameid">@drstonyhills</span>
                </a>
                <small class="published-time">
                    <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                </small>
                <ul class="actions">
                    <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                    <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                    <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                    <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                </ul>
            </div>
            <div class="stream-item-body wrapword">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
            <div class="stream-item-footer">
                <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
            </div>
            <div class="stream-item-media"></div>
            <div class="stream-item-interaction">
                <ul class="stream-items">
                    <li class="stream-item-li">
                        <div class="stream-item-container">
                            <div class="stream-item-header">
                                <a class="publisher-profile" href="#">
                                    <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                                    <strong class="profile-name">Livingstone Fultang</strong>
                                    <span class="profile-nameid">@drstonyhills</span>
                                </a>
                                <small class="published-time">
                                    <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                                </small>
                                <ul class="actions">
                                    <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                                    <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                                    <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                                    <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                                </ul>
                            </div>
                            <div class="stream-item-body wrapword">This is just a comments</div>
                            <div class="stream-item-footer">
                                <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </li>
    <li class="stream-item-li">
        <div class="stream-item-container">
            <div class="stream-item-header">
                <a class="publisher-profile" href="#">
                    <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                    <strong class="profile-name">Livingstone Fultang</strong>
                    <span class="profile-nameid">@drstonyhills</span>
                </a>
                <small class="published-time">
                    <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                </small>
                <ul class="actions">
                    <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                    <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                    <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                    <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                </ul>
            </div>
            <div class="stream-item-body wrapword">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
            <div class="stream-item-footer">
                <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
            </div>
        </div>
    </li>
    <li class="stream-item-li">
        <div class="stream-item-container">
            <div class="stream-item-header">
                <a class="publisher-profile" href="#">
                    <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                    <strong class="profile-name">Livingstone Fultang</strong>
                    <span class="profile-nameid">@drstonyhills</span>
                </a>
                <small class="published-time">
                    <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                </small>
                <ul class="actions">
                    <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                    <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                    <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                    <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                </ul>
            </div>
            <div class="stream-item-body wrapword">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
            <div class="stream-item-footer">
                <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
            </div>
        </div>
    </li>
    <li class="stream-item-li">
        <div class="stream-item-container">
            <div class="stream-item-header">
                <a class="publisher-profile" href="#">
                    <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                    <strong class="profile-name">Livingstone Fultang</strong>
                    <span class="profile-nameid">@drstonyhills</span>
                </a>
                <small class="published-time">
                    <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                </small>
                <ul class="actions">
                    <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                    <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                    <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                    <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                </ul>
            </div>
            <div class="stream-item-body wrapword">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
            <div class="stream-item-footer">
                <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
            </div>
        </div>
    </li>
    <li class="stream-item-li">
        <div class="stream-item-container">
            <div class="stream-item-header">
                <a class="publisher-profile" href="#">
                    <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                    <strong class="profile-name">Livingstone Fultang</strong>
                    <span class="profile-nameid">@drstonyhills</span>
                </a>
                <small class="published-time">
                    <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                </small>
                <ul class="actions">
                    <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                    <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                    <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                    <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                </ul>
            </div>
            <div class="stream-item-body wrapword">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
            <div class="stream-item-footer">
                <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
            </div>
        </div>
    </li>
    <li class="stream-item-li">
        <div class="stream-item-container">
            <div class="stream-item-header">
                <a class="publisher-profile" href="#">
                    <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                    <strong class="profile-name">Livingstone Fultang</strong>
                    <span class="profile-nameid">@drstonyhills</span>
                </a>
                <small class="published-time">
                    <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                </small>
                <ul class="actions">
                    <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                    <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                    <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                    <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                </ul>
            </div>
            <div class="stream-item-body wrapword">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
            <div class="stream-item-footer">
                <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
            </div>
        </div>
    </li>
</ol>