<div class="grid sidetabs vertical-tabs">
    <div class="row">
        <div class="big-board grid padding-20">
            <div class="row">

                <div class="col fifth"><img class="thumbnail width-100" src="http://localhost/joomla/components/com_tuiyo/files/avatars/62/thumb200/62_255_6a00e54fb7301c88340133f61013eb970b800wi.jpg" width="100"></div>
                <div class="col four-fifths">
                    <ul class="page-info" style="margin-left: 15px">
                        <li class="signup-date">Member since 10 months ago</li>
                        <li class="signin-date">Last logged in about 6 days ago</li>
                        <!-- Date of Birth -->
                        <!-- Contact Information -->
                        <li class="company-element"><a href="#">Stonyhills LLC</a></li>
                        <li class="email-element"><a href="mailto:livingstonefultang@gmail.com">livingstonefultang@gmail.com</a></li>
                        <!--CUSTOM SOCIAL INFORMATION-->
                    </ul>
                </div>

                <div class="clear"></div>
            </div>
        </div>
    </div>



    <div clas="row">
        <!-- Side Tab Navigation -->
        <nav class="sidetab-switch" style="text-align: right">
            <ul style="margin-right: 9px;">
                <li><a  class="default-sidetab current" href="#account" rel="~data:/account">Welcome</a></li>
                <li><a  href="#groups" rel="~data:/groups">Readr</a></li>
                <li><a  href="#connections" rel="~data:/connections">Analytics</a></li>
            </ul>

        </nav>
    </div>
    <!--    <div class="row">
            <div class="notification attention">Hey drstonyhills</div>
        </div>-->
    <div class="row">
        <div class="col whole wrap">
            <ul id="dashboard-prompts">
                <li class="upload-prompt prompt-link">
                    <p class="prompt-icon"><a href="<?php echo $this->link('/content/photo/create'); ?>"><?php echo _('Upload Photos'); ?></a></p>
                    <h3 class="prompt-title"><a href="<?php echo $this->link('/content/photo/create'); ?>"><?php echo _('Upload Photos'); ?></a></h3>
                    <p class="prompt-description"><?php echo _('They say a picture is more than a thousand words, Show us what you\'ve been up to'); ?></p>
                </li>
                <li class="article-prompt prompt-link">
                    <p class="prompt-icon"><a href="<?php echo $this->link('/content/article/create'); ?>"><?php echo _('Got a story to tell?'); ?></a></p>
                    <h3 class="prompt-title"><a href="<?php echo $this->link('/content/article/create'); ?>"><?php echo _('Got a story to tell?'); ?></a></h3>
                    <p class="prompt-description"><?php echo _('From a short one-liner, to a full 6000-word rant about topics you care about. Come on, tell us your story'); ?></p>
                </li>
                <li class="video-prompt prompt-link">
                    <p class="prompt-icon"><a href="<?php echo $this->link('/content/video/create'); ?>"><?php echo _('Share a video story'); ?></a></p>
                    <h3 class="prompt-title"><a href="<?php echo $this->link('/content/video/create'); ?>"><?php echo _('Share a video story'); ?></a></h3>
                    <p class="prompt-description"><?php echo _('Where your video phone at? Share your videos, movies, short-films, screen casts, etc.. with the world'); ?></p>
                </li>
                <li class="question-prompt prompt-link">
                    <p class="prompt-icon"><a href="<?php echo $this->link('/content/question/create'); ?>"><?php echo _('Ask a Question'); ?></a></p>
                    <h3 class="prompt-title"><a href="<?php echo $this->link('/content/question/create'); ?>"><?php echo _('Ask a Question'); ?></a></h3>
                    <p class="prompt-description"><?php echo _('Lots of helpful people waiting to provide awesome answers to your pressing questions. All you got to do is just ask'); ?></p>
                </li>
                <li class="event-prompt prompt-link">
                    <p class="prompt-icon"><a href="<?php echo $this->link('/content/event/create'); ?>"><?php echo _('Create and Event'); ?></a></p>
                    <h3 class="prompt-title"><a href="<?php echo $this->link('/content/event/create'); ?>"><?php echo _('Plan an Event'); ?></a></h3>
                    <p class="prompt-description"><?php echo _('A big day coming up, not sure what to do? Come on in and let us help you plan and invite your friends'); ?></p>
                </li>
                <li class="audio-prompt prompt-link">
                    <p class="prompt-icon"><a href="<?php echo $this->link('/content/audio/create'); ?>"><?php echo _('Want to say something?'); ?></a></p>
                    <h3 class="prompt-title"><a href="<?php echo $this->link('/content/audio/create'); ?>"><?php echo _('Say it out loud'); ?></a></h3>
                    <p class="prompt-description"><?php echo _('Plug in your mic and tell the world exactly what is on your mind! Or share and audio track.'); ?></p>
                </li>
                <li class="favourite-prompt prompt-link">
                    <p class="prompt-icon"><a href="<?php echo $this->link('/content/items/favourites'); ?>"><?php echo _('Your Favourites'); ?></a></p>
                    <h3 class="prompt-title"><a href="<?php echo $this->link('/content/items/favourites'); ?>"><?php echo _('Your Favourites'); ?></a></h3>
                    <p class="prompt-description"><?php echo _('We\'ve filtered the large amount of photos, articles and videos to sumize the things we feel will interest you the most. Check these out'); ?></p>
                </li>
                <li class="reader-prompt prompt-link">
                    <p class="prompt-icon"><a href="<?php echo $this->link('/content/items/read'); ?>"><?php echo _('News Reader'); ?></a></p>
                    <h3 class="prompt-title"><a href="<?php echo $this->link('/content/items/read'); ?>"><?php echo _('News Reader'); ?></a></h3>
                    <p class="prompt-description"><?php echo _('Just want to see what your friends and connections are upto? Come into the news room'); ?></p>
                </li>
                <li class="account-prompt prompt-link">
                    <p class="prompt-icon"><a href="<?php echo $this->link('/member/account/settings'); ?>"><?php echo _('Tell us more about yourself'); ?></a></p>
                    <h3 class="prompt-title"><a href="<?php echo $this->link('/member/account/settings'); ?>"><?php echo _('Tell us more about yourself'); ?></a></h3>
                    <p class="prompt-description"><?php echo _('Surely your life-story is more than just what comes out of your mouth! Tell us more more more ;) '); ?></p>
                </li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
</div>