<form id="form" name="login_form" method="post" action="/user/session/start">
<!--    <fieldset style="width: 100%">-->

        <label><?php echo _("Username"); ?>
            <span class="small"><?php echo _("Alternatively, use registered email"); ?></span>
        </label>
        <input type="text" name="user_name_id" id="user_name_id" style="width:50%" size="40" placeholder="<?php echo _("e.g JohnDoe90"); ?>" />

        <label><?php echo _("Password"); ?>
            <span class="small">&nbsp</span>
        </label>
        <input type="password" name="user_password" id="user_password" style="width:50%" />

        <input type="checkbox" name="user_session_save" /><span><?php echo _("Save session for 14 days") ; ?></span>
        
        <div class="clear" style="margin-bottom: 20px"></div>

        <button type="submit"><?php echo _("Start Session"); ?></button>

<!--    </fieldset>-->
</form>