
<form>
    <fieldset>
        <h3><?php echo _('Privacy settings'); ?></h3>
        <p><?php echo _('Here you can control what aspects of your profile are visible to specific people, groups, connections and the public.'); ?></p>
        <div class="grid" style="margin-bottom: 0px">
            <div class="row" style="padding-top: 6px">
                <div class="col" style="width: 65%;">
                    <strong>Profile privacy</strong>
                    <p><?php echo _("You choose what information in your profile you want to make visible to specific individuals, to circles or to everyone."); ?></p>
                </div>
                <div class="col dashboard" style="width: 35%" align="right"><a href="/profile/view" class="button"><?php echo _("Edit profile privacy"); ?></a></div>
                
            </div>
            <div class="row" style="padding-top: 6px">
                <div class="col" style="width: 65%;">
                    <strong>Visibility in search results</strong>
                    <p><?php echo _("Your name and any other fields that you make public in your profile are searchable on the web and may appear in Google Search results."); ?></p>
                </div>
                <div class="col dashboard" style="width: 35%" align="right"><input type="checkbox" rel="tooltip" checked="checked" title="<?php echo _('Visible in search Results'); ?>" name="dashboard_n[wall_post]" /><span><?php echo _("Visible in search"); ?></span></div>
                
            </div>
            <div class="row" style="padding-top: 6px">
                <div class="col" style="width: 65%;">
                    <strong>Block Lists</strong>
                    <p><?php echo _("You can specify who can automatically tag you with a tag linked to your Google Profile, whether to attach the location where you took the photos when you upload them and whether to include a Photos tab in your public profile."); ?></p>
                </div>
                <div class="col dashboard" style="width: 35%" align="right"><a href="#" class="button"><?php echo _("View block lists"); ?></a></div>
                
            </div>
            <div class="row" style="padding-top: 6px">
                <div class="col" style="width: 65%;">
                    <strong>Photos and videos</strong>
                    <p><?php echo _("You can specify who can automatically tag you with a tag linked to your Google Profile, whether to attach the location where you took the photos when you upload them and whether to include a Photos tab in your public profile."); ?></p>
                </div>
                <div class="col dashboard" style="width: 35%" align="right"><a href="#" class="button"><?php echo _("Edit photo privacy"); ?></a></div>
                
            </div>            
            <div class="row" style="padding-top: 6px">
                <div class="col" style="width: 65%;">
                    <strong>Connected accounts</strong>
                    <p><?php echo _("Improve your profile identity be connecting your external accounts like facebook and twitter. You can control how you will like data from your external profiles to be displayed on your profile."); ?></p>
                </div>
                <div class="col dashboard" style="width: 35%" align="right"><a href="#" class="button"><?php echo _("Edit connected accounts"); ?></a></div>
                
            </div>
            <div class="row" style="padding-top: 6px">
                <div class="col" style="width: 65%;">
                    <strong>API Data access</strong>
                    <p><?php echo _("You can specify who can automatically tag you with a tag linked to your Google Profile, whether to attach the location where you took the photos when you upload them and whether to include a Photos tab in your public profile."); ?></p>
                </div>
                <div class="col dashboard" style="width: 35%" align="right"><a href="#" class="button"><?php echo _("Reset API Keys"); ?></a></div>
                
            </div>
            
            <hr class="hr-ccc" />

            <div class="row" style="padding-top: 6px">
                <div class="col" style="width: 80%;">
                    <input type="text" name="email" id="title" style="width: 420px" placeholder="<?php echo _("Enter a name or username.."); ?>" />
                </div>
                <div class="col dashboard" style="width: 20%"><a href="#" class="button"><?php echo _("Preview"); ?></a></div>
                
            </div>
        </div>

    </fieldset>
</form>
