<section role="timeline" id="timelinebar">
    <div class="menu yearbook" style="display:none">
        <ul style="position:relative">

            <li><a href="#">2007</a></li>
            <li><a href="#">2008</a></li>
            <li><a href="#" style="color: #fff">2009</a></li>
            <li><a href="#" style="color: #fff">2010</a></li>
            <li class="active"><a href="#" style="color: #1495cc">2011</a></li>
            <div class="clearFloat"></div>
        </ul>
        <ul>


        </ul>
    </div>
    <div class="menu monthbook" style="display: none">
        <ul style="font-size: 14px">
            <li><a href="#">January</a></li>
            <li><a href="#">Febraury</a></li>
            <li><a href="#">March</a></li>
            <li><a href="#">April</a></li>
            <li><a href="#">May</a></li>
            <li><a href="#">June</a></li>
            <li><a href="#">July</a></li>
            <li><a href="#">August</a></li>
            <li class="active"><a href="#" style="color: #1495cc">September</a></li>
            <li><a href="#">October</a></li>
            <li><a href="#">November</a></li>
            <li><a href="#">December</a></li>
            <div class="clearFloat"></div>
        </ul>
    </div>
    <div class="menu daybook" style="display: block">
        <ul style="position: relative">
            <li><a href="#" style="color: #666; border-right: 1px solid #ccc; font-weight: bolder">September 2011</a></li>

            <li><a href="#">01</a></li>
            <li><a href="#">02</a></li>
            <li><a href="#">03</a></li>
            <li><a href="#">04</a></li>
            <li><a href="#">05</a></li>
            <li><a href="#">06</a></li>
            <li><a href="#">07</a></li>
            <li><a href="#">08</a></li>
            <li><a href="#">09</a></li>
            <li><a href="#">10</a></li>
            <li><a href="#">11</a></li>
            <li><a href="#">12</a></li>
            <li><a href="#">13</a></li>
            <li><a href="#">14</a></li>
            <li><a href="#">15</a></li>
            <li><a href="#">16</a></li>
            <li><a href="#">17</a></li>
            <li><a href="#">18</a></li>
            <li><a href="#">19</a></li>
            <li><a href="#">20</a></li>
            <li><a href="#">21</a></li>
            <li><a href="#">22</a></li>
            <li><a href="#">23</a></li>
            <li><a href="#">24</a></li>
            <li class="active"><a href="#" style="color: #1495cc">25</a></li>
            <li><a href="#">26</a></li>
            <li><a href="#">27</a></li>
            <li><a href="#">28</a></li>
            <li><a href="#">29</a></li>
            <li><a href="#">30</a></li>
            <li><a href="#">31</a></li>
            <li><a href="#" style="color: #666; border-left: 1px solid #ccc; position:absolute; right: 0">Show all</a></li>
            <div class="clearFloat"></div>
        </ul>
    </div>

    <div class="titlebar">
        <div id="content-announce">
            <img id="content-image" class="CoolClock:swissRail:24 localTime" width="48" height="48" style="width: 48px; height: 48px; width: 48px;
height: 48px;
margin-right: 10px;
float: left;" src="http://dribbble.s3.amazonaws.com/users/39190/avatars/original/Untitled-2.png?1307437455" />
            <a href="/index.php" style="color: #272727; font-size: 2em"><span class="location">Alexander Cherevich</span></a>
            <p style="line-height: 1em"><span class="locale">Россия</span> &ndash; <span class="locale-time">Wednesday, 28 September</span></p>
        </div>
    </div>

</section>