



<div class="sidetabs vertical-tabs">

    <!-- Side Tab Navigation -->
    <nav class="sidetab-switch">
        <ul>
            <li><a class="default-sidetab current" href="#plat"><?php echo _('Platform'); ?></a></li>
            <li><a  href="#featured"><?php echo _('Featured'); ?></a></li>

            <li><a  href="#recommendations"><?php echo _('Activity'); ?></a></li>
            <li><a  href="#newest"><?php echo _('Interactions'); ?></a></li>
            <li><a  href="#popular"><?php echo _('Demographics'); ?></a></li>
        </ul>

    </nav>
    <!-- /Side Tab Navigation -->

    <div class="sidetab  default-sidetab" id="addnew" style="display: block; "> 
        <form class="wrap">
            
                
                <p><?php echo _('Take an analytical view of your platform. View activity, demographics, and more..'); ?></p>
                <hr class="hr-ccc" />
           
        </form>
    </div>
</div>
