<div class="sidetabs vertical-tabs">

    <!-- Side Tab Navigation -->
    <nav class="sidetab-switch">
        <ul>
            <li><a  class="default-sidetab current" href="#system"><?php echo _('System'); ?></a></li>
            <li><a  href="#server"><?php echo _('Server'); ?></a></li>
            <li><a  href="#client"><?php echo _('Client'); ?></a></li>
            <li><a  href="#external"><?php echo _('Applications'); ?></a></li>
        </ul>

    </nav>
    <div class="sidetab" id="external" style="display:none; padding: 0"> 

        <div class="sidetabs horizontal-tabs">

            <!-- Side Tab Navigation -->
            <nav class="sidetab-switch" style="min-height: 800px">
                <ul>
                    <li><a  class="default-sidetab current" href="#facebook"><?php echo _('Facebook'); ?></a></li>
                    <li><a  href="#twitter"><?php echo _('Twitter'); ?></a></li>
                    <li><a  href="#twitter"><?php echo _('Google+'); ?></a></li>
                    <li><a  href="#twitter"><?php echo _('LlinkedIn'); ?></a></li>
                    <li><a  href="#twitter"><?php echo _('MySpace'); ?></a></li>
                </ul>
            </nav>
            <div class="sidetab default-sidetab" id="facebook" style="display:block; ">
                Facebook Settings
            </div>
        </div>

    </div>
    <!-- /Side Tab Navigation -->
    <div class="sidetab default-sidetab" id="system" style="display:block; "> 
        <form>
            <fieldset class="wrap">
                <h4 class="margin-top-0"><?php echo _('Platform settings'); ?></h4>

                <p><?php echo _('The details requested here are important in governing how the platform works. Read through and complete each accordingly'); ?></p>

                <label><?php echo _('Website Name'); ?>
                    <span class="small"><?php echo _('A compelling name for your website'); ?></span>
                </label>
                <input type="text" name="site-name" id="site-name" style="width:50%" placeholder="e.g MySocialNetwork" />



                <label><?php echo _('Offline Message'); ?>
                    <span class="small"><?php echo _('Brief maintenance message'); ?></span>
                </label>
                <textarea name="offline-message" class="wysiwyg" id="offline-message" style="width: 60%!important" placeholder="<?php echo _('This message will be displayed when the site is offline'); ?>" ></textarea>

                <label><?php echo _('WebSite URL'); ?>
                    <span class="small"><?php echo _('The site address'); ?></span>
                </label>
                <input type="text" name="site-address" id="site-address" style="width: 50%" placeholder="http://www.mydomain.com/" />

                <hr class="hr-ccc" style="margin-top: 20px"/>



                <label><?php echo _('New user\'s registered as..'); ?>
                    <span class="small"></span>
                </label>
                <select name="default-role" id="default-role" style="width: 250px">
                    <option value="registered">Registered</option>
                </select>
                <label style="margin: 15px 0 10px">
                    <input type="checkbox" name="allow-registraion" checked="checked" value="1" />
                    <?php echo _('Allow new user Registration'); ?>
                    <span class="small"></span>
                </label>
                <hr class="hr-ccc" style="margin-top: 20px"/>

                <label><?php echo _('Platform E-mail'); ?>
                    <span class="small"><?php echo _('An email account, from and to which system mails are addressed'); ?></span>
                </label>
                <input type="text" name="email" id="email" style="width: 50%" placeholder="contact@mydomain.com" />


                <label><?php echo _("Mail Server"); ?>
                    <span class="small"><?php echo _("The outgoing mail server address"); ?></span>
                </label>
                <input type="text" name="mail-server" id="mail-server" style="width: 50%" placeholder="webmail.mydomain.com:80"/>

                <label><?php echo _("Mail server username"); ?>
                    <span class="small"></span>
                </label>
                <input type="text" name="mail-server-username" id="email" style="width: 250px" placeholder="e.g JohnDoe" />
                <label><?php echo _("Mail server password"); ?>
                    <span class="small"></span>
                </label>
                <input type="text" name="mail-server-password" id="mail-server-password" style="width: 250px" />

                <hr class="hr-ccc" style="margin-top: 20px"/>
                <label><?php echo _("Site Meta description"); ?>
                    <span class="small"></span>
                </label>
                <textarea name="site-meta-description" id="site-meta-description" style="width: 50%" rows="3" ></textarea>

                <label><?php echo _("Site Meta keywords"); ?>
                    <span class="small"></span>
                </label>
                <textarea name="site-meta-keywords" id="site-meta-keywords" style="width: 50%" rows="3" ></textarea>

                <div class="row">
                    <div class="col two-third">
                        <label><?php echo _('Add site name to page titles'); ?>
                            <span class="small"></span>
                        </label>
                        <select name="timezone" id="password" style="width: 250px">
                            <option value="0"><?php echo _('No, Leave as is'); ?></option>
                            <option value="1"><?php echo _('Yes, Prepend site name'); ?></option>
                            <option value="2"><?php echo _('Yes, Append site name'); ?></option>
                        </select>
                    </div>
                </div>

                <hr class="hr-ccc"/>

                <div class="row">
                    <div class="col whole">
                        <label><?php echo _('Timezone'); ?>
                            <span class="small"></span>
                        </label>
                        <select name="timezone" id="password" style="width:50% ">
                            <option value="-12.0">(GMT -12:00) Eniwetok, Kwajalein</option>
                            <option value="-11.0">(GMT -11:00) Midway Island, Samoa</option>
                            <option value="-10.0">(GMT -10:00) Hawaii</option>
                            <option value="-9.0">(GMT -9:00) Alaska</option>
                            <option value="-8.0">(GMT -8:00) Pacific Time (US &amp; Canada)</option>
                            <option value="-7.0">(GMT -7:00) Mountain Time (US &amp; Canada)</option>
                            <option value="-6.0">(GMT -6:00) Central Time (US &amp; Canada), Mexico City</option>
                            <option value="-5.0">(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima</option>
                            <option value="-4.0">(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz</option>
                            <option value="-3.5">(GMT -3:30) Newfoundland</option>
                            <option value="-3.0">(GMT -3:00) Brazil, Buenos Aires, Georgetown</option>
                            <option value="-2.0">(GMT -2:00) Mid-Atlantic</option>
                            <option value="-1.0">(GMT -1:00 hour) Azores, Cape Verde Islands</option>
                            <option value="0.0" selected="selected">(GMT) Western Europe Time, London, Lisbon, Casablanca</option>
                            <option value="1.0">(GMT +1:00 hour) Brussels, Copenhagen, Madrid, Paris</option>
                            <option value="2.0">(GMT +2:00) Kaliningrad, South Africa</option>
                            <option value="3.0">(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg</option>
                            <option value="3.5">(GMT +3:30) Tehran</option>
                            <option value="4.0">(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi</option>
                            <option value="4.5">(GMT +4:30) Kabul</option>
                            <option value="5.0">(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent</option>
                            <option value="5.5">(GMT +5:30) Bombay, Calcutta, Madras, New Delhi</option>
                            <option value="5.75">(GMT +5:45) Kathmandu</option>
                            <option value="6.0">(GMT +6:00) Almaty, Dhaka, Colombo</option>
                            <option value="7.0">(GMT +7:00) Bangkok, Hanoi, Jakarta</option>
                            <option value="8.0">(GMT +8:00) Beijing, Perth, Singapore, Hong Kong</option>
                            <option value="9.0">(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk</option>
                            <option value="9.5">(GMT +9:30) Adelaide, Darwin</option>
                            <option value="10.0">(GMT +10:00) Eastern Australia, Guam, Vladivostok</option>
                            <option value="11.0">(GMT +11:00) Magadan, Solomon Islands, New Caledonia</option>
                            <option value="12.0">(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col quater">
                        <label><?php echo _('Default Locale'); ?>
                            <span class="small"></span>
                        </label>
                        <select name="language" id="password" style="width: 99%">
                            <option value="en_GB"><?php echo _('English - United Kingdom (en_GB)'); ?></option>
                            <option value="fr_FR"><?php echo _('French - France (fr_FR)'); ?></option>
                            <option value="de_DE"><?php echo _('German - Germany (de_DE)'); ?></option>
                        </select>
                    </div>
                    <div class="col quater">
                        <label><?php echo _('Date format'); ?>
                            <span class="small"></span>
                        </label>
                        <select name="dateformat" id="dateformat" style="width: 100%">
                            <option value="default"><?php echo _('Time difference'); ?></option>
                            <option value="locale"><?php echo _('Locale time format'); ?></option>
                        </select>
                    </div>

                </div>


                <div class="clear"></div>

                <hr class="hr-ccc" style="margin-top: 15px"/>

                <button type="submit"><?php echo _('Save System settings'); ?></button>

            </fieldset>

        </form>

    </div>
</div>