<div class="sidetabs vertical-tabs">
    <ul class="tabs">
        <li><a  href="#addpermissions" data-toggle="tab"><?php echo _('Permissions'); ?></a></li>
        <li><a class="active current" href="#authoritylists" data-toggle="tab"><?php echo _('Authorities'); ?></a></li>
        <li><a  href="#memberauthority" data-toggle="tab"><?php echo _('Members'); ?></a></li>
        <li><a  href="#permissionconsole" data-toggle="tab"><?php echo _('Console'); ?></a></li>
    </ul>
    <div class="tab-content">
        <div class="sidetab tab-pane" id="addpermissions" style="display:none; "> 
            <form method="POST" action="<?php echo $this->link('/system/admin/settings/privacy/permissions/add'); ?>">

                <div class="grid wrap"> 

                    <fieldset>
                        <div class="row clearfix wrap">
                            <p><?php echo _('Note that by default, all un-defined permissions are denied. Where thesame permission is defined to the parent, it will be inherited. Also permission heiracchy is Special > Modify > Execute > View, implying an authority with Special permissions can View, Execute and Modify objects in an AoR. An authority with permission to Modify can, automatically View the Objects in this area, etc'); ?></p>
                            <div class="col three-fifths">
                                <label> <?php echo _('Authority'); ?><em class="mandatory">*</em>
                                    <span class="small"><?php echo _('Select an authority to modify'); ?></span>
                                </label>
                                <select name="area-authority"  style="width:315px">
                                    <?php foreach ($this->get("authorities") as $e): ?>
                                        <option value="<?php echo $e['authority']['authority_id'] ?>"><?php echo str_repeat(' - ', (int) $e['authority']['indent']) . ' ' . $e['authority']['authority_title'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="col two-fifths">
                                <label> <?php echo _('Area Title'); ?><em class="mandatory">*</em>
                                    <span class="small"><?php echo _('Area of Responsibility'); ?></span>
                                </label>
                                <input type="text" name="area-title" style="width:215px" placeholder="e.g Marketplace" />
                            </div>
                        </div>
                        <div class="row clearfix whole">
                            <div class="col three-fifths"> 
                                <label> <?php echo _('Area URI'); ?><em class="mandatory">*</em>
                                    <span class="small"><?php echo _('URI to the Area or Object'); ?></span>
                                </label>
                                <input type="text" name="area-uri" style="width:315px" placeholder="Area URI e.g /marketplace/*" />
                            </div>
                            <div class="col fifth">
                                <label> <?php echo _('Type'); ?><em class="mandatory">*</em></label>
                                <select name="area-action"  style="width:100px">
                                    <option value="view"><?php echo _('View'); ?></option>
                                    <option value="execute"><?php echo _('Execute'); ?></option>
                                    <option value="modify"><?php echo _('Modify'); ?></option>
                                    <option value="special"><?php echo _('Special'); ?></option>
                                </select>
                            </div>
                            <div class="col fifth">
                                <label> <?php echo _('Permission'); ?><em class="mandatory">*</em></label>
                                <select name="area-permission"  style="width:107px">
                                    <option value="inherit"><?php echo _('Inherited'); ?></option>
                                    <option value="allow"><?php echo _('Allowed'); ?></option>
                                    <option value="deny" selected="selected"><?php echo _('Denied'); ?></option>
                                </select>
                            </div>
                        </div>
                        <hr class="hr-ccc" />

                        <div class="grid wrap">
                            <div class="row">
                                <div class="col half" align="left">
                                    <button type="submit" style=" margin-left: 0px"><?php echo _('Save Authority Permissions'); ?></button>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <?php foreach ($this->authorities as $e): if (is_array($e['authority']['permissions'])) : ?>
                            <fieldset class="grid wrap">
                                <h3><?php echo sprintf(_("%s"), $e['authority']['authority_title']); ?></h3>

                                <hr class="hr-ccc" />

                                <?php foreach ($e['authority']['permissions'] as $permission): ?>
                                    <div class="row" style="padding: 3px 0">
                                        <div class="col three-fifths"><a href="<?php echo $this->link('/system/admin/settings/privacy.json') ?>" rel="modal" title="<?php echo _("Areas affected by this permission") ?>"><span title="<?php echo $permission['permission_area_uri'] ?>" rel="tooltip"><?php echo $permission['permission_title'] ?></span></a></div>
                                        <div class="col two-fifths">
                                            <div class="col third"><?php echo _(ucfirst($permission['permission_type'])) ?></div>
                                            <div class="col third permission-value"><font class="<?php echo $permission['permission'] ?>"><?php echo _(ucfirst($permission['permission'])) ?></font></div>
                                            <div class="col third"><a href="#"><?php echo _('Revoke'); ?></a></div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </fieldset>
                        <?php
                        endif;
                    endforeach;
                    ?>
                </div>

                <input type="hidden" name="authority-id"  value="" />
            </form>
        </div>

        <div class="tab-pane " id="memberauthority" style="display: none; "> 

            Member authority lists

        </div>

        <div class="tab-pane" id="permissionconsole" style="display: none; "> 
            Permission Console
        </div>

        <div class="tab-pane active" id="authoritylists" style="display: block; "> 

            <form class="wrap" method="POST" action="<?php echo $this->link('/system/admin/settings/privacy/edit'); ?>">
                <!--        <fieldset class="white-background wrap">-->

                <fieldset>
                    <div class="pageEl table">
                        <h4 class="margin-top-0"><?php echo _('Authority List'); ?></h4>

<?php foreach ($this->authorities as $e): ?>

                            <div  class="row clearfix fieldListItem">

                                <div class="col" style="width: 90%;" >
                                        <?php for ($i = 0; $i < $e['authority']['indent']; $i++): ?><a class="indenter" >-</a> <?php endfor; ?>
                                    <a href="#editPermissions" rel="modal" title="<?php echo sprintf(_("Permissions for the '%s' authority"), $e['authority']['authority_title']); ?>">
    <?php echo $e['authority']['authority_title'] ?>
                                    </a> 
                                    <p style="display: inline; overflow: hidden"> &HorizontalLine; <?php echo $e['authority']['authority_description'] ?></p>
                                </div>
                                <div class="col dashboard" style="width: 10%" align="right">
                                    <a rel="modal" href="#editAuthority" title="<?php echo sprintf(_("Modify the '%s' authority"), $e['authority']['authority_title']); ?>">
    <?php echo _('Modify'); ?>
                                    </a>   
                                </div>
                                <div class="clear"></div>
                            </div>

                            <hr class="hr-ccc" />

<?php endforeach; ?>

                    </div>
                </fieldset>
                <fieldset>

                    <!-- Lists Items -->
                    <h4><?php echo _('Add Authority'); ?></h4>
                    <p><?php echo _("An authority is a role in an area of responsibility (AoR). A curator is the head of an authority, who can create and grant permissions to users in that authority, or sub authority. A permission is an authorization to, access, modify or execute an object or operation, granted to an authority or user by a curator. Some authorities are automatically generated. For instance geographical and age authorities, can be used to limit permission by location, and age respectively. A unified command/control plan (UCP), is a predifined map of authority to permission to operation in an Area of Responsibility. For instance, The Authority 'Moderators' granted the permission to 'modifiy' all objects in the 'Post submission' Area of responsibility. The UCP is defined by the Master Administrator, who is the curator or curators") ?></p>

                    <hr class="hr-ccc"  />

                    <label><?php echo _('Authority Title'); ?><em class="mandatory">*</em><span class="small"><?php echo _('A name to identify this group of members'); ?></span>
                    </label>
                    <input type="text" name="authority-title" id="authority-title" style="width:450px" placeholder="<?php echo _('e.g Global Investors'); ?>" />

                    <label><?php echo _('Authority Description'); ?>
                        <span class="small"><?php echo _('Just so you remember why you added this authority, add an optional description'); ?></span>
                    </label>
                    <textarea name="authority-description" id="authority-description" style="width:450px" placeholder="<?php echo _('e.g All the users who invested in our groups'); ?>"></textarea>


                    <label><?php echo _('Parent Authority'); ?>
                        <span class="small"><?php echo _('Make this a sub-authority child of another to inherit parent permissions?'); ?></span>
                    </label>
                    <select name="authority-parent" id="authority-parent" style="width: 450px">
                            <?php foreach ($this->get("authorities") as $e): ?>
                            <option value="<?php echo $e['authority']['authority_id'] ?>">
                            <?php echo str_repeat(' - ', (int) $e['authority']['indent']) . ' ' . $e['authority']['authority_title'] ?>
                            </option>
<?php endforeach; ?>
                    </select>

                    <hr class="hr-ccc" style="margin-top: 20px" />

                    <input type="hidden" name="authority-id"  value="" />

                    <div class="grid wrap">
                        <div class="row">
                            <div class="col half" align="left">
                                <button type="submit" style=" margin-left: 0px"><?php echo _('Save Authority'); ?></button>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </form>

        </div>
    </div>
</div>
