<?php
/**
 * 
 * HTML5 Theme for Tuiyosocial
 *
 * LICENSE: This source file is subject to version 3.01 of the GPL license
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/licenses/gpl.txt.  If you did not receive a copy of
 * the GPLv3 License and are unable to obtain it through the web, please
 * send a note to license@tuiyo.co.uk so we can mail you a copy immediately.
 *
 * @author     Original Author <livingstonefultang@gmail.com>
 * @copyright  2011 The StonyhillsHQ Group
 * @license    http://www.gnu.org/licenses/gpl.txt.  GNU GPL License 3.01
 * 
 */
?>
<!doctype html>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en"> <!--<![endif]-->
    <head>
        <title><?php echo $this->getPageTitle(); ?></title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="<?php echo $this->getPageDescription(); ?>">
        <meta name="author" content="<?php echo $this->getPageAuthor(); ?>">
        <meta name="keywords" content="<?php echo $this->getPageAuthor(); ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--[if IE]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
        <!--[if lte IE 7]>
                <script src="js/IE8.js" type="text/javascript"></script><![endif]-->
        <!--[if lt IE 7]>

        <link rel="stylesheet" type="text/css" media="all" href="css/ie6.css"/><![endif]-->


        <link rel="icon" href="/<?php echo $this->getTemplateName() ?>/favicon.ico" type="image/x-icon">
        <link rel="apple-touch-icon" href="/<?php echo $this->getTemplateName() ?>/apple-touch-icon.png">

        <!-- Style Sheets -->
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/style.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/forms.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/reset.css" />

        <!-- Plugin Style Sheets -->
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/jquery.tipsy.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/jquery.datatables.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/jquery.facebox.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/jquery.datepicker.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/jquery.fileinput.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/jquery.fullcalendar.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/jquery.wysiwyg.css" />

        <!-- Scripts -->
        <script src='/<?php echo $this->getTemplateName() ?>/js/libs/jquery-1.7.1.min.js'></script>
        <script src='/<?php echo $this->getTemplateName() ?>/js/libs/jquery-ui.min.js'></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/libs/modernizr-1.7.min.js" type="text/javaScript"></script>
    </head>

    <body class="home">

        <section role="admin-body" class="clearfix" id="<?php echo $this->get('pageid') ?>" style="width: 100%; border-bottom: 1px solid #ccc">
            <?php if ((boolean) $this->hasPosition("alerts")): ?>
                <section role="notifier">
                    <!-- Notifications -->
                    <?php $this->position("alerts"); ?>
                    <!--/Notifications -->
                </section>

            <?php endif; ?>
            <section id="welcome" class="page">

                <div class="grid">
                    <div class="row">
                        <div class="col sixth" style="max-width: 200px; min-width: 200px">
                            <h1 class="site-logo clearfix"><a href="<?php echo $this->link('/index.php'); ?>">tuiyosocial</a></h1>
                            <nav id="side-nav" class="colapsible-nav">
                                <ul>
                                    <li class="adm-dashboar current"><a id="dashboard-menu" href="<?php echo $this->link('/system/admin/index'); ?>"><?php echo _('Dashboard'); ?></a></li>


                                    <li>
                                        <a id="content-menu" href="#" rel="colapsible"><?php echo _('Content'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('New'); ?>">81</span></a>
                                        <div>
                                            <ul class="child">
                                                <li class="cnt-new"><a href="<?php echo $this->link('/system/admin/content/add'); ?>"><?php echo _('Add new...'); ?></a></li>
                                                <li class="cnt-articles"><a href="<?php echo $this->link('/system/admin/content/lists/articles'); ?>"><?php echo _('Articles'); ?> <span class="smaller bold" rel="tooltip" title="<?php echo _('New'); ?>">30</span></a></li>
                                                <li class="cnt-photos"><a href="<?php echo $this->link('/system/admin/content/lists/photos'); ?>"><?php echo _('Photos'); ?></a></li>
                                                <li class="cnt-videos"><a href="<?php echo $this->link('/system/admin/content/lists/videos'); ?>"><?php echo _('Videos'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('New'); ?>">20</span></a></li>
                                                <li class="cnt-audio"><a href="<?php echo $this->link('/system/admin/content/lists/audio'); ?>"><?php echo _('Audio'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('New'); ?>">31</span></a></li>
                                                <li class="cnt-questions"><a href="<?php echo $this->link('/system/admin/content/lists/questions'); ?>"><?php echo _('Questions'); ?></a></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li>
                                        <a id="extension-menu" href="#" rel="colapsible"><?php echo _('Extensions'); ?></a>
                                        <div>
                                            <ul class="child">
                                                <li class="ext-new"><a href="<?php echo $this->link('/system/admin/extensions/add'); ?>"><?php echo _('Add new...'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('New Extension'); ?>">1</span></a></li>
                                                <li class="ext-extensions"><a href="<?php echo $this->link('/system/admin/extensions/lists'); ?>"><?php echo _('Installed Extensions'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('Updates Available'); ?>">5</span></a></li>
                                                <li class="ext-repositories"><a href="<?php echo $this->link('/system/admin/extensions/repositories'); ?>"><?php echo _('Manage Repositories'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('Repositories'); ?>">3</span></a></li>
                                            </ul>
                                        </div>
                                    </li>

                                    <li>
                                        <a id="network-menu" href="#" rel="colapsible"><?php echo _('Network'); ?></a>
                                        <div>
                                            <ul class="child">
                                                <li class="ntw-new"><a href="<?php echo $this->link('/system/admin/network/add'); ?>"><?php echo _('Add new..'); ?></a></li>
                                                <li class="ntw-members"><a href="<?php echo $this->link('/system/admin/network/lists/members'); ?>"><?php echo _('All members'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('Members'); ?>">3156</span></a></li>                      
                                                <li class="ntw-analytics"><a href="<?php echo $this->link('/system/admin/network/analytics'); ?>"><?php echo _('Analytics'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('Unique visits today!'); ?>">123</span></a></li>
                                                <li class="ntw-relationships"><a href="<?php echo $this->link('/system/admin/network/relationships'); ?>"><?php echo _('Relationships'); ?></a></li>
                                                <li class="ntw-networks"><a href="<?php echo $this->link('/system/admin/network/extended'); ?>"><?php echo _('Extended networks'); ?></a></li>
                                            </ul>
                                        </div>
                                    </li>

                                    <li>
                                        <a id="preferences-menu" href="#" rel="colapsible"><?php echo _('Preferences'); ?></a>
                                        <div>
                                            <ul class="child">
                                                <li class="set-config"><a href="<?php echo $this->link('/system/admin/settings/configuration'); ?>"><?php echo _('Configuration'); ?></a></li>
                                                <li class="set-privacy"><a href="<?php echo $this->link('/system/admin/settings/privacy'); ?>"><?php echo _('Permissions'); ?></a></li>
                                                <li class="set-appearance"><a href="<?php echo $this->link('/system/admin/settings/appearance'); ?>"><?php echo _('Appearance'); ?></a></li>
                                                <li class="set-maintenance"><a href="<?php echo $this->link('/system/admin/settings/maintenance'); ?>"><?php echo _('Maintenance'); ?></a></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li>
                                        <a id="tasks-menu" href="#" rel="colapsible"><?php echo _('Tasks'); ?></a>
                                        <div>
                                            <ul class="child">
                                                <li class="adm-to-dolist"><a href="<?php echo $this->link('/system/admin/manager/lists/tasks'); ?>"><?php echo _('To-do Lists'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('New'); ?>">22</span></a></li>                      
                                                <li class="adm-moderation-queue"><a href="<?php echo $this->link('/system/admin/manager/moderation'); ?>"><?php echo _('Moderation Queue'); ?><span class="smaller bold" rel="tooltip" title="<?php echo _('Needing Attention'); ?>">100+</span></a></li>
                                                <li class="adm-announcements"><a href="<?php echo $this->link('/system/admin/manager/announcements'); ?>"><?php echo _('Announcements'); ?></a></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="adm-support"><a id="support-menu" href="<?php echo $this->link('/system/admin/index'); ?>"><?php echo _('Support'); ?></a></li>

                                </ul>
                            </nav>
                        </div>
                        <div class="wrap clearfix" id="adminpanel" style="border-left: 1px solid #ccc; margin-left: 200px; background:#fff; min-height: 800px">
                            <div class="clearfix">
                                <?php $this->position("admin:panel") ?>
                                <?php $this->position("do:debugger") ?>
                            </div>

                        </div>
                    </div>
                </div>

            </section>
        </section>

        <!-- scripts concatenated and minified via ant build script-->
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins.js" type="text/javaScript"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/script.js" type="text/javaScript"></script>

        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.tipsy.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.widgetize.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.wysiwyg.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.facebox.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.datatables.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.datepicker.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.fileinput.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.fullcalendar.min.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.flot.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/excanvas.js"></script>

        <!-- end scripts-->

        <!--[if lt IE 7 ]>
          <script src="js/libs/dd_belatedpng.js"></script>
          <script>DD_belatedPNG.fix("img, .png_bg");</script>
        <![endif]-->

        <script type="text/javascript" src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.cookies.js"></script>
        <script type="text/javascript" >
            //@TODO Replace the jaaulde tools with the system js library tools
            //Plus using cookies to do this is probably overkill! @TODO Re-work menu states in menu sys
            //$('.colapsible-nav ul li div').hide();
            if(jaaulde.utils.cookies.get){
                $('nav ul li a[rel=colapsible]').each(function(i, anchor){
                    var menuid = $(anchor).attr("id") ;
                    $(this).next().css("display", jaaulde.utils.cookies.get( menuid ) );
                })
            } 
            $('nav ul li a[rel=colapsible]').click(function(e) {
                e.preventDefault();
                //$(this).parent().siblings().find('div').slideUp();
                if(jaaulde.utils.cookies.set){ 
                    var menuid = $(this).attr("id"),
                        menustate = ( $(this).next().is(":hidden") ) ? "block" : "none";                  
                        jaaulde.utils.cookies.set( menuid , menustate ); 
                }
                $(this).next().slideToggle();
                return false;
            });
        </script>

    </body>

</html>