<form action="<?php echo $this->link('/'); ?>" method="POST">
    <fieldset class="timeline-item-publisher">
        <div class="row-fluid bottom-pad">
            <div class="span12 map-canvas" style="height:250px"></div>
        </div>
        <div class="row-fluid">
            <textarea class="span12 focused" rows="3"></textarea>
        </div>
        <div class="timeline-item-publisher-actions">
            <div class="btn-toolbar" style="margin-bottom: 9px">
                <div class="btn-group">
                    <button class="btn btn-success"><i class=" icon-map-marker"></i> Check-in</button>
                </div>
                <div class="btn-group">
                    <button type="submit" class="btn">Attach</button>
                    <button  class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="icon-picture"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="icon-folder-close"></i> Create an Album</a></li>
                        <li><a href="#"><i class="icon-film"></i>  Add a short video</a></li>
                    </ul>     
                </div>
                <div class="btn-group pull-right">
                    <button type="submit" class="btn btn-primary" href="#">Publish</button>
                    <button  class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="icon-lock"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="icon-pencil"></i> To everyone</a></li>
                        <li><a href="#"><i class="icon-trash"></i>  To friends only</a></li>
                        <li><a href="#"><i class="icon-ban-circle"></i> Ban</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="i"></i> Save as draft</a></li>
                    </ul>     
                </div>
            </div>

        </div>
    </fieldset>
    <hr />
    <ol class="timeline-items" id="main-timeline">
        <li class="timeline-item-li">
            <div class="timeline-item-container">
                <div class="timeline-item-header">
                    <a class="publisher-profile" href="#">
                        <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                        <strong class="profile-name">Livingstone Fultang</strong>
                        <span class="profile-nameid">@drstonyhills</span>
                    </a>
                    <small class="published-time">
                        <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                    </small>
                    <ul class="actions">
                        <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                        <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                        <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                        <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                    </ul>
                </div>
                <div class="timeline-item-body">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
                <div class="timeline-item-footer">
                    <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
                </div>
            </div>
        </li>
        <li class="timeline-item-li">
            <div class="timeline-item-container">
                <div class="timeline-item-header">
                    <a class="publisher-profile" href="#">
                        <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                        <strong class="profile-name">Livingstone Fultang</strong>
                        <span class="profile-nameid">@drstonyhills</span>
                    </a>
                    <small class="published-time">
                        <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                    </small>
                    <ul class="actions">
                        <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                        <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                        <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                        <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                    </ul>
                </div>
                <div class="timeline-item-body">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
                <div class="timeline-item-footer">
                    <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
                </div>
            </div>
        </li>
        <li class="timeline-item-li">
            <div class="timeline-item-container">
                <div class="timeline-item-header">
                    <a class="publisher-profile" href="#">
                        <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                        <strong class="profile-name">Livingstone Fultang</strong>
                        <span class="profile-nameid">@drstonyhills</span>
                    </a>
                    <small class="published-time">
                        <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                    </small>
                    <ul class="actions">
                        <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                        <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                        <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                        <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                    </ul>
                </div>
                <div class="timeline-item-body">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
                <div class="timeline-item-footer">
                    <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
                </div>
                <div class="timeline-item-media"></div>
            </div>
            <div class="timeline-item-interaction">
                <ul class="timeline-items">
                    <li class="timeline-item-li">
                        <div class="timeline-item-container">
                            <div class="timeline-item-header">
                                <a class="publisher-profile" href="#">
                                    <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                                    <strong class="profile-name">Livingstone Fultang</strong>
                                    <span class="profile-nameid">@drstonyhills</span>
                                </a>
                                <small class="published-time">
                                    <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                                </small>
                                <ul class="actions">
                                    <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                                    <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                                    <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                                    <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                                </ul>
                            </div>
                            <div class="timeline-item-body">This is just a comments</div>
                            <div class="timeline-item-footer">
                                <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </li>
        <li class="timeline-item-li">
            <div class="timeline-item-container">
                <div class="timeline-item-header">
                    <a class="publisher-profile" href="#">
                        <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                        <strong class="profile-name">Livingstone Fultang</strong>
                        <span class="profile-nameid">@drstonyhills</span>
                    </a>
                    <small class="published-time">
                        <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                    </small>
                    <ul class="actions">
                        <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                        <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                        <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                        <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>
                    </ul>
                </div>
                <div class="timeline-item-body">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
                <div class="timeline-item-footer">
                    <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
                </div>
            </div>
        </li>
        <li class="timeline-item-li">
            <div class="timeline-item-container">
                <div class="timeline-item-header">
                    <a class="publisher-profile" href="#">
                        <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                        <strong class="profile-name">Livingstone Fultang</strong>
                        <span class="profile-nameid">@drstonyhills</span>
                    </a>
                    <small class="published-time">
                        <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                    </small>
                    <ul class="actions">
                        <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                        <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                        <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                        <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                    </ul>
                </div>
                <div class="timeline-item-body">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
                <div class="timeline-item-footer">
                    <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
                </div>
            </div>
        </li>
        <li class="timeline-item-li">
            <div class="timeline-item-container">
                <div class="timeline-item-header">
                    <a class="publisher-profile" href="#">
                        <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                        <strong class="profile-name">Livingstone Fultang</strong>
                        <span class="profile-nameid">@drstonyhills</span>
                    </a>
                    <small class="published-time">
                        <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                    </small>
                    <ul class="actions">
                        <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                        <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                        <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                        <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>

                    </ul>
                </div>
                <div class="timeline-item-body">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
                <div class="timeline-item-footer">
                    <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
                </div>
            </div>
        </li>
        <li class="timeline-item-li">
            <div class="timeline-item-container">
                <div class="timeline-item-header">
                    <a class="publisher-profile" href="#">
                        <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                        <strong class="profile-name">Livingstone Fultang</strong>
                        <span class="profile-nameid">@drstonyhills</span>
                    </a>
                    <small class="published-time">
                        <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                    </small>
                    <ul class="actions">
                        <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                        <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                        <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                        <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>
                    </ul>
                </div>
                <div class="timeline-item-body">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
                <div class="timeline-item-footer">
                    <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
                </div>
            </div>
        </li>
        <li class="timeline-item-li">
            <div class="timeline-item-container">
                <div class="timeline-item-header">
                    <a class="publisher-profile" href="#">
                        <img class="profile-avatar" src="https://si0.twimg.com/profile_images/1734672571/logo_normal.png" alt="Livingstone Fultang">
                        <strong class="profile-name">Livingstone Fultang</strong>
                        <span class="profile-nameid">@drstonyhills</span>
                    </a>
                    <small class="published-time">
                        <a href="/#!/Torettox84/status/161005839744897025" title="8:42 AM - 22 Jan 12"><span class="_timestamp" data-time="1327221758000" data-long-form="true">1h ago</span></a>
                    </small>
                    <ul class="actions">
                        <li class="action-like"><a href="#"><span class="like" title="Like">Like</span></a></li>
                        <li class="action-reply"><a href="#"><span class="reply" title="Reply">Reply</span></a></li>
                        <li class="action-repost"><a href="#"><span class="repost" title="Repost">Repost</span></a></li>
                        <li class="action-delete"><a href="#"><span class="delete" title="Repost">Delete</span></a></li>
                    </ul>
                </div>
                <div class="timeline-item-body">Is it just me or is the latest chrome having issues loading assets? whats that with all the Content-Type: null ? for css, js and most files</div>
                <div class="timeline-item-footer">
                    <div class="context"><a class="profile-link" href="/#!/drstonyhills" data-user-id="15968381"><span>View 38 responses</span></a></div>
                </div>
            </div>
        </li>
    </ol>
    <div class="row-fluid">
        <button class="btn span12">Load more</button>
    </div>
</form>