<form>
    <fieldset>
        <strong>Whilst at <a href="#">Bar Loco</a> did you..</strong>
        <ol class="top-pad">
            <li>Try a pint of Tuborg?</li>
            <li>Meet Charlotte?</li>
            <li>Play a game of darts?</li>
        </ol>
    </fieldset>
    <fieldset class="top-pad">
        <strong>Have you met the following?</strong>
        <ol class="top-pad">
            <li>Gaspard Santoni</li>
            <li>Butafogo Guillame-Ribera</li>
        </ol>
    </fieldset>

</form>