<form>
    <fieldset>
        <strong class="timeline-tips-title">Whilst at <a href="#">Bar Loco</a> did you..</strong>
        <ol class="timeline-tips-list">
            <li>
                <span class="tip-title">Attend the pancake eating competition</span>
                <small class="tip-popularity pull-right">20%</small>
                <span class="suggestion-info">Suggested by @drstonyhills</span>
                <div class="progress mini-bar progress-danger progress-bar">
                    <div class="bar" style="width: 20%;"></div>
                </div>
                <div class="tip-actions"><a href="#" class="tip-response"><i class="icon-ok"></i></a> <a href="#" class="tip-response"><i class="icon-remove"></i></a></div>
            </li>
            <li>
                <span class="tip-title">Try a discounted pint of Tuborg.</span>  
                <small class="tip-popularity pull-right">53%</small>
                <span class="suggestion-info">Suggested by @drstonyhills</span>
                <div class="progress mini-bar progress-success progress-bar">
                    <div class="bar" style="width: 53%;"></div>
                </div>
                <div class="tip-actions"><a href="#" class="tip-response"><i class="icon-ok"></i></a> <a href="#" class="tip-response"><i class="icon-remove"></i></a></div>
            </li>
            <li>
                <span class="tip-title">Meet Rudolf Edinau.</span>
                <small class="tip-popularity pull-right">20%</small>
                <span class="suggestion-info">Suggested by @drstonyhills</span>
                <div class="progress mini-bar progress-danger progress-bar">
                    <div class="bar" style="width: 20%;"></div>
                </div>
                <div class="tip-actions"><a href="#" class="tip-response"><i class="icon-ok"></i></a> <a href="#" class="tip-response"><i class="icon-remove"></i></a></div>
            </li>
            <li>
                <span class="tip-title">Play a game of darts.</span>
                <small class="tip-popularity pull-right">83%</small>
                <span class="suggestion-info">Suggested by @drstonyhills</span>
                <div class="progress mini-bar progress-success progress-bar">
                    <div class="bar" style="width: 83%;"></div>
                </div>
                <div class="tip-actions"><a href="#" class="tip-response"><i class="icon-ok"></i></a> <a href="#" class="tip-response"><i class="icon-remove"></i></a></div>
            </li>
        </ol>
    </fieldset>
    <fieldset class="top-pad">
        <strong class="timeline-tips-title">Have you met the following?</strong>
        <ol class="timeline-tips-list">
            <li>Gaspard Santoni</li>
            <li>Butafogo Guillame-Ribera</li>
        </ol>
    </fieldset>

</form>