<div class="grid">
    <h1 style="position:relative; padding-right: 50px;" class="clearfix">Fultang Livingstone Kimbi Fatele</h1>
    <hr class="hr-ccc" />
    <div class="row">
        <div class="col span4">
            <ul class="page-info">
                <li class="signup-date">Member since 10 months ago</li>
                <li class="signin-date">Last logged in about 6 days ago</li>
                <!-- Date of Birth -->
                <li class="company-element">Born on the&nbsp;<a href="#">14th of March</a></li>
                <!-- Contact Information -->
                <li class="company-element">Works at&nbsp;<a href="#">Stonyhills LLC</a></li>
                <li class="email-element"><a href="mailto:livingstonefultang@gmail.com">livingstonefultang@gmail.com</a></li>
                <!--CUSTOM SOCIAL INFORMATION-->
            </ul>

        </div>
        <div class="col span12">
            <div class="wrap" style="padding-left: 4px; width: 680px">
                <a href="#" class="thumbnail">
                    <img  src="http://placehold.it/680x200" width="680" height="200" />
                </a>
            </div>
        </div>
    </div>
    <hr class="hr-ccc" />

    <div class="row">
        <div class="col span4"><h2>Followers&nbsp;<small><a href="#">View all</a></small></h2></div>
        <div class="col span12">
            <div class="padding-left-25 wrap">
                <ul class="media-grid">
                    <?php for ($i = 0; $i < 14; $i++): ?>
                        <li>
                            <a href="#">
                                <img class="thumbnail" src="http://placehold.it/80x80" alt="" width="80" height="80" />
                            </a>
                        </li>
                    <?php endfor; ?>
                </ul>
            </div>
        </div>
    </div>
    <hr class="hr-ccc" />
    <div class="row">
        <div class="col span4"><h2>Following&nbsp;<small><a href="#">View all</a></small></h2></div>
        <div class="col span12">
            <div class="padding-left-25 wrap">
                <ul class="media-grid">
                    <?php for ($i = 0; $i < 14; $i++): ?>
                        <li>
                            <a href="#">
                                <img class="thumbnail" src="http://placehold.it/80x80" alt="" width="80" height="80" />
                            </a>
                        </li>
                    <?php endfor; ?>
                </ul>
            </div>
        </div>
    </div>
    <hr class="hr-ccc" />
    <div class="row">
        <div class="col span4"><h2>About Me</h2></div>
        <div class="col span12">
            <div class="padding-left-25 wrap">


                <div class="entry">
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, <a href="#">links look like this</a>. tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, <strong>bolded word</strong> <a href="#">tempor sit amet</a>, ante. Donec eu <em>this area in italics</em> libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
                    <p><span id="more-5"></span></p>
                    <h2>This is an h2 subtitle</h2>
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, <strong>bolded word</strong> <a href="#">tempor sit amet</a>, ante. Donec eu <em>this area in italics</em> libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
                    <h3>This is an h3 subtitle</h3>
                    <ul>
                        <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
                        <li>Aliquam tincidunt mauris eu risus.</li>
                        <li>Vestibulum auctor dapibus neque.
                            <ul>
                                <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
                                <li>Aliquam tincidunt mauris eu risus.</li>
                            </ul>
                        </li>
                    </ul>
                    <h4>This is an h4 subtitle</h4>
                    <ol>
                        <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
                        <li>Aliquam tincidunt mauris eu risus.</li>
                        <li>Vestibulum auctor dapibus neque.
                            <ol>
                                <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
                                <li>Aliquam tincidunt mauris eu risus.</li>
                            </ol>
                        </li>
                    </ol>
                    <blockquote><p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. <a href="#">Donec eu</a> libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
                    </blockquote>
                    <h5>This is an h5 subtitle</h5>
                    <p>Here is some preformatted text:</p>
                    <pre><code>#header h1 a {
	display: block;
	width: 300px;
	height: 80px;
}</code></pre>
                    <p>..and some longer code examples:</p>
                    <pre><code>(http://angry-birds.net/maps/chapter-4/theme-9/level-9-8/).css(
http://angry-birds.net/maps/chapter-4/theme-9/level-9-8/);f=e.css(
http://angry-birds.net/maps/chapter-4/theme-9/level-9-8/,c.css(this[a],
http://angry-birds.net/maps/chapter-4/theme-9/level-9-8/;if(c.css(this[a],
http://angry-birds.net/maps/chapter-4/theme-9/level-9-8/)&amp;&amp;this.style){j.display=c.css(this,
http://angry-birds.net/maps/chapter-4/theme-9/level-9-8/);this.elem.style.display=a?a:this.options.display;if(c.css(this.elem,
http://angry-birds.net/maps/chapter-4/theme-9/level-9-8/],rb=s.defaultView&amp;&amp;s.defaultView.getComputedStyle,Pa=c.support.cssFloat?
http://angry-birds.net/maps/chapter-4/theme-9/level-9-8/},cur:function(a){if(this.elem[this.prop]!=null&amp;&amp;(!this.elem.style||this.elem.style[this.prop]==null))return%20this.elem[this.prop];return(a=parseFloat(c.css(this.elem,this.prop,a)))&amp;&amp;a&gt;-10000?a:parseFloat(c.curCSS(this.elem,this.prop))||0},custom:function(a,b,d){function%20f(j){return%20e.step(j)}this.startTime=J();this.start=a;this.end=b;this.unit=d||this.unit||</code></pre>
                </div> 
            </div>
        </div>
    </div>
</div>