<div class="grid">
    <div class="row">
        <div class="col whole">
            
            <div class="padding-left-20">
                <div class="sidetabs vertical-tabs" >

                    <!-- Side Tab Navigation -->
                    <nav class="sidetab-switch">
                        <ul>
                            <li><a  class="default-sidetab current" href="#account" rel="~data:/account">Account</a></li>


                            <li><a  href="#profile" rel="~data:/profile">Profile</a></li>            
                            <li><a  href="#privacy">Privacy</a></li>
                            <li><a  href="#appearance">Appearance</a></li>
                            <li><a  href="#notifications">Notifications</a></li>
                        </ul>

                    </nav>


                    <div class="sidetab" id="applications" style="display: block; ">
                        <h3>jQuery Full Calendar Plugin</h3>
                    </div>
                    <div class="sidetab" id="profile" style="display: block; ">
                        <h3>Profile</h3>
                    </div>
                    <div class="sidetab  default-sidetab" id="account" style="display: block; ">
                        <?php echo $this->layout('settings_account'); ?>
                    </div>
                    <div class="sidetab" id="privacy" style="display: block; ">
                        <?php echo $this->layout('settings_privacy'); ?>
                    </div>
                    <div class="sidetab" id="notifications" style="display: block; ">
                        <?php echo $this->layout('settings_notifications'); ?>
                    </div>
                    <div class="sidetab wrap" id="appearance" style="display: block; ">
                        <?php echo "the appearance tab"; ?>
                    </div>
                    <div class="sidetab" id="connections" style="display: block; ">
                        <h3>Connections, groups, friends, external profiles</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>