<!doctype html>
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <title><?php echo $this->getPageTitle(); ?></title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="<?php echo $this->getPageDescription(); ?>">
        <meta name="author" content="<?php echo $this->getPageAuthor(); ?>">
        <meta name="keywords" content="<?php echo $this->getPageAuthor(); ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--[if IE]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
        <!--[if lte IE 7]>
                <script src="js/IE8.js" type="text/javascript"></script><![endif]-->
        <!--[if lt IE 7]>

        <link rel="stylesheet" type="text/css" media="all" href="css/ie6.css"/><![endif]-->

        <link rel="icon" href="/<?php echo $this->getTemplateName() ?>/favicon.ico" type="image/x-icon">

        <!-- Style Sheets -->
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/style.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/forms.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/reset.css" />

        <!-- Plugin Style Sheets -->
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/jquery.tipsy.css" />

        <!-- Scripts -->
        <script src='/<?php echo $this->getTemplateName() ?>/js/libs/jquery-1.7.1.min.js'></script>
        <script src='/<?php echo $this->getTemplateName() ?>/js/libs/jquery-ui.min.js'></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/libs/modernizr-1.7.min.js" type="text/javaScript"></script>
    </head>
    <body class="login">
        <section role="main">
            <div class="clearfix" align="center" style="width: 135px; margin: auto">
                <a class="logo clearfix" href="/index.php">Logo</a>
            </div>

            <!-- Login box -->
            <article id="login-box">

                <div class="article-container">
                    <!-- Notifications -->
                    <?php $this->position("alerts"); ?>
                    <!--/Notifications -->

                    <form id="form" name="form" method="post" action="/member/account/update">

                        <?php //$this->position('body'); ?> <!--No need for a body here -->

                        <label><?php echo _('Full Name'); ?><em class="mandatory">*</em>
                            <span class="small"><?php echo _('Will be displayed on your profile'); ?></span>
                        </label>
                        <input type="text" name="user_name" id="user_name" style="width:100%" placeholder="<?php echo _('e.g John Doe'); ?>" />

                        <label><?php echo _('Unique Username'); ?><em class="mandatory">*</em>
                            <span class="small"><?php echo _('Aa-Zz,0-9 short'); ?></span>
                        </label>
                        <input type="text" name="user_name_id" id="user_name_id" style="width:100%" size="40" placeholder="<?php echo _('e.g JohnDoe90'); ?>" />

                        <label><?php echo _('Valid Email address'); ?><em class="mandatory">*</em>
                            <span class="small"><?php echo _('Important info sent to this address'); ?></span>
                        </label>
                        <input type="text" name="user_email" id="user_email" style="width:100%" placeholder="<?php echo _('e.g john.doe@example.com'); ?>" />

                        <label><?php echo _('Password'); ?><em class="mandatory">*</em>
                            <span class="small"><?php echo _('Minimum of 8 characters'); ?></span>
                        </label>
                        <input type="password" name="user_password" id="user_password" style="width:100%" />

                        <label><?php echo _('Verify you Password'); ?><em class="mandatory">*</em></label>
                        <input type="password" name="user_password_2" id="user_password_2" style="width:100%" />

                        <input type="checkbox" name="user_accepted_terms" /><span><?php echo _('You accept to the terms and conditions'); ?></span>

                        <div class="clear" style="margin-bottom: 20px"></div>

                        <button type="submit"><?php echo _('Create account'); ?></button>

                        <!-- /Login box -->
                        <ul class="login-links">
                            <li><a href="/member/session/start/"><?php echo _("Already have an Account?"); ?></a></li>
                            <li><a href="/index.php"><?php echo _("Back to home-page"); ?></a></li>
                        </ul>
                    </form>

                </div>

            </article>


        </section>
        
        <?php $this->position("do:debugger") ?>
        
        <!-- JS Libs at the end for faster loading -->

        <script src="/<?php echo $this->getTemplate(); ?>/js/plugins/jquery.facebox.js"></script>
        <script src="/<?php echo $this->getTemplate(); ?>/js/plugins/jquery.tipsy.js"></script>
        <script src="/<?php echo $this->getTemplate(); ?>/js/plugins/jquery.datatables.js"></script>
        <script src="/<?php echo $this->getTemplate(); ?>/js/plugins/jquery.widgetize.js"></script>
        <script src="/<?php echo $this->getTemplate(); ?>/js/plugins/jquery.datepicker.js"></script>
        <script src="/<?php echo $this->getTemplate(); ?>/js/plugins/jquery.fileinput.js"></script>
        <script src="/<?php echo $this->getTemplate(); ?>/js/plugins/jquery.fullcalendar.min.js"></script>
        <script src="/<?php echo $this->getTemplate(); ?>/js/plugins/excanvas.js"></script>
        <script src="/<?php echo $this->getTemplate(); ?>/js/plugins/jquery.visualize.js"></script>
        <script src="/<?php echo $this->getTemplate(); ?>/js/script.js"></script>
        <script src="/<?php echo $this->getTemplate(); ?>/js/plugins.js"></script>

    </body>
</html>