<!doctype html>
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <title><?php echo $this->getPageTitle(); ?></title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="<?php echo $this->getPageDescription(); ?>">
        <meta name="author" content="<?php echo $this->getPageAuthor(); ?>">
        <meta name="keywords" content="<?php echo $this->getPageAuthor(); ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--[if IE]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
        <!--[if lte IE 7]>
                <script src="js/IE8.js" type="text/javascript"></script><![endif]-->
        <!--[if lt IE 7]>

        <link rel="stylesheet" type="text/css" media="all" href="css/ie6.css"/><![endif]-->

        <link rel="icon" href="/<?php echo $this->getTemplateName() ?>/favicon.ico" type="image/x-icon">

        <!-- Style Sheets -->
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/style.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/forms.css" />
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/reset.css" />

        <!-- Plugin Style Sheets -->
        <link rel="stylesheet" href="/<?php echo $this->getTemplateName() ?>/css/jquery.tipsy.css" />

        <!-- Scripts -->
        <script src='/<?php echo $this->getTemplateName() ?>/js/libs/jquery-1.7.1.min.js'></script>
        <script src='/<?php echo $this->getTemplateName() ?>/js/libs/jquery-ui.min.js'></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/libs/modernizr-1.7.min.js" type="text/javaScript"></script>
    </head>
    <body class="login">
        <section role="main">
            <div class="clearfix" align="center" style="width: 135px; margin: auto">
                <a class="logo clearfix" href="/index.php">Logo</a>
            </div>
            <article id="login-box">

                <div class="article-container">
                    <?php $this->position("alerts"); ?>
                    <form id="form" name="login_form" method="post" action="/member/session/start">                       
                        <?php //$this->position('body'); ?> 
                        <label><?php echo _("E-mail or Username"); ?><em class="mandatory">*</em>
                            <span class="small"><?php echo _('or even your Member ID'); ?></span>
                        </label>
                        <input type="text" name="user_name_id" id="user_name_id" style="width:100%" size="40" placeholder="<?php echo _("e.g JohnDoe90@gmail.com"); ?>" />
                        <label><?php echo _("Password or API Key"); ?><em class="mandatory">*</em>
                            <span class="small">&nbsp</span>
                        </label>
                        <input type="password" name="user_password" id="user_password" style="width:100%" />
                        <input type="checkbox" name="user_session_save" /><span><?php echo _("Save session for 14 days"); ?></span>
                        <div class="clear" style="margin-bottom: 20px"></div>
                        <input type="hidden" name="auth_handler" value="" />
                        <input type="hidden" name="redirect" value="" />
                        <button type="submit"><?php echo _("Start Session"); ?></button>
                    </form>
                    <ul class="login-links clearfix">
                        <li><a href="<?php echo $this->link('/index.php'); ?>"><?php echo _("Forgot your password?"); ?></a></li>
                        <li><a href="<?php echo $this->link('/member/account/create'); ?>"><?php echo _("Register a new account"); ?></a></li>
                        <li><a href="<?php echo $this->link('/index.php'); ?>"><?php echo _("Back to Homepage"); ?></a></li>
                    </ul>
                </div>
            </article>
        </section>

        <?php $this->position("do:debugger") ?>

        <!-- scripts concatenated and minified via ant build script-->
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins.js" type="text/javaScript"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/script.js" type="text/javaScript"></script>

        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.tipsy.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.widgetize.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.wysiwyg.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.facebox.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.datatables.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.datepicker.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.fileinput.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.fullcalendar.min.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/jquery.flot.js"></script>
        <script src="/<?php echo $this->getTemplateName() ?>/js/plugins/excanvas.js"></script>

        <!-- end scripts-->

        <!--[if lt IE 7 ]>
          <script src="js/libs/dd_belatedpng.js"></script>
          <script>DD_belatedPNG.fix("img, .png_bg");</script>
        <![endif]-->


    </body>
</html>