<div class="titlebar" style="padding-left: 0px; padding-top: 0px">
    <div class="grid">
        <div class="row">
            <div class="col half">
                <div id="content-announce">
                    <img id="content-image" width="48" height="48" style="width: 48px;height: 48px;margin-right: 10px;float: left;" src="http://dribbble.s3.amazonaws.com/users/28310/avatars/original/63_wallpaper_iphone_apple_galaxy_by_jetc21_normal.jpg?1305139928" />
                    <a href="/index.php" style="color: #272727; font-size: 1.5em; display:block; margin-bottom: 5px;"><span class="title-id">Livingstone Fultang</span></a>
                    <p style="line-height: 1em"><span class="locale"></span> <span class="locale-time">Account Settings</span></p>
                </div>
            </div>
            <div class="col half"></div>
			<div class="clear"></div>
        </div>
    </div>
</div>